
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const APP_DATA_SUCCESS = 'APP_DATA_SUCCESS';
export const APP_SESSION_DATA = 'APP_SESSION_DATA';
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
export const APP_SESSION_AMOUNT = 'APP_SESSION_AMOUNT';

